### PR TITLE
staffposition list view

### PR DESCRIPTION
**Pull request by kate-mills**
Hope this is is what you were wanting.

### CODE REVIEW

**Review by babybunny — APPROVED** [review]
This looks great. Very straight forward.

**Comment by thebpc** [comment]
Hi team, Boris form DeepCode here. We noticed (thanks @babybunny for reporting) that our service is blocking you. Usually, DeepCode takes seconds to analyze a Pull Request, but your Pull requests have invertedly ended-up in a strange state. 
Our team is looking into it and we will report here shortly.
If you need me, in the meantime you can reach me at boris@deepcode.ai

**Comment by vraychev** [comment]
retry deepcode

**Comment by thebpc** [comment]
vraychev above manually restarted the check by DeepCode and this completed. 
Apologies for the delay, we had an obscure bug that prevented us to alert GitHub that the analysis completed.
On average our analysis completes in 1 to 2 seconds. So please do let us know if you experience any future problems or have other feedback: deepcode@deepcode.ai

**Comment by babybunny** [comment]
Thanks for fixing it!  Good to know also that this was a strange state and
nothing to expect in the future. Are you putting any alerts on place in
case a similar situation occurs?

**Comment by thebpc** [comment]
Yes indeed, we will be tracking state internally so if there is a restart
or other weird events causing a process to end-up not closing we will be
automatically restarting it.

**Pull request merged**
