### PR TITLE
migrate data and populate search

### PR DESCRIPTION
**Pull request by andy-d**

### CODE REVIEW

**Comment by babybunny** [comment]
ready for review?

**Review by babybunny — COMMENTED** [review]
gosh I've totally lost track of this PR.  It is still something that should be merged?  looks like it won't hurt.

**Comment by andy-d** [comment]
I’m as clueless as you about this. Did search come up in the meeting at all? If so and they are interested we could look at this. Otherwise it may not be worth it right?

**Comment by babybunny** [comment]
oops I think this includes some code to perform a schema change (Program gets a new key format)

and it includes some code in ndb_models.py Program.get_or_create that expects the schema change to be complete as well.   

Will revert now and take a closer look later.

**Pull request merged**
