### PR TITLE
standardize whitespace in python files

### PR DESCRIPTION
**Pull request by andy-d**

### CODE REVIEW

**Review by babybunny — COMMENTED** [review]
We were trying to standardize on two-space indentation. Had been running autopep8 opportunistically.

See, for example, https://github.com/babybunny/rebuildingtogethercaptain/commit/45cd46513acf5896534356af7327f3cc1682d390

If this was auto-generated by a command, please include the command in the description so it can be found and repeated in the future.

**Comment by andy-d** [comment]
Ah ok you prefer 2 spaces? I'm happy either way but defer to you.

**Comment by babybunny** [comment]
yeah prefer 2 spaces

**Comment by andy-d** [comment]
To answer your question this wasn't auto-generated with a single shell command, I ran reformat code in each python module and optimize imports. But I can update my preferences to two spaces if you prefer that, I'm indifferent like I said. Actually two was my preference before the world seemed to standardize on four for some reason, probably because people write blocks that are too long. Anyway I'll update to 2.

**Comment by andy-d** [comment]
*reformat code from PyCharm

**Pull request closed without merging**
